# mouse support
set -g mouse on

# faster prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# better colors
set -g default-terminal "screen-256color"

# start pane index at 1
set -g base-index 1
setw -g pane-base-index 1

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# auto restore last saved session
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# run TPM
run '~/.tmux/plugins/tpm/tpm'
